"""
Generate the full Luzart modifier+aggregation infrastructure for 8 player stats.

Per stat (8 stats × ~10 SOs = ~80 SOs):
  - 3 ModDef (AddNormal / AddRatio / Multiply)
  - 3 AssetModifier_ContributeToAggregatedNumber
  - 1 AssetNumber_Constant (Base from current StatsCfg_Player value)
  - 4 AssetNumber_Aggregation (TotalAddNormal/TotalAddRatio/TotalAddSubRatio/TotalMultiply)
  - 1 AssetNumber_SimpleBoosted (Final = (Base + TotalAddNormal) × TotalAddSubRatio × TotalMultiply)

Output: Assets/_Main/Data/ModifierAndInGame/Player/<Stat>/...
"""
import os, sys, io, json, uuid, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

INDEX = json.load(open('docs/asset-guid-index.json', encoding='utf-8'))

# Script GUIDs (from earlier index build)
SG = {
    'AssetModifierDefinition':                 '683c122f2bdf57949a71d648c73db2c3',
    'AssetModifier_ContributeToAggregatedNumber': 'c6e54ce9a0886de4fbf23f641cc5ade3',
    'AssetNumber_Constant':                    '538fdae1998489b498206b2d9d675495',
    'AssetNumber_Aggregation':                 'b691dab8d6c2f16449978ce0d28b190c',
    'AssetNumber_SimpleBoosted':               '8657fc305e8686c429dcfb1d5b10d381',
}

# (StatName, base value from StatsCfg_Player)
STATS = [
    ('HPMax',     1000.0),
    ('ATK',       10.0),
    ('Speed',     4.0),
    ('Cooldown',  1.0),   # most skills baseline 1s
    ('FireSpeed', 10.0),
    ('Heal',      0.0),
    ('Armor',     0.0),
    ('RangeFind', 8.0),
]

CREATED = {}  # name -> guid

def gen(): return uuid.uuid4().hex

def write_asset(folder, fname, body, sub_guid=None):
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, fname).replace(os.sep, '/')
    guid = sub_guid or gen()
    with open(path, 'w', encoding='utf-8', newline='\n') as f: f.write(body)
    with open(path + '.meta', 'w', encoding='utf-8', newline='\n') as f:
        f.write(f'fileFormatVersion: 2\nguid: {guid}\nNativeFormatImporter:\n  externalObjects: {{}}\n  mainObjectFileID: 11400000\n  userData: \n  assetBundleName: \n  assetBundleVariant: \n')
    return guid

def so_header(script_guid, name, class_id=''):
    return (f'%YAML 1.1\n%TAG !u! tag:unity3d.com,2011:\n--- !u!114 &11400000\n'
            f'MonoBehaviour:\n  m_ObjectHideFlags: 0\n  m_CorrespondingSourceObject: {{fileID: 0}}\n'
            f'  m_PrefabInstance: {{fileID: 0}}\n  m_PrefabAsset: {{fileID: 0}}\n  m_GameObject: {{fileID: 0}}\n'
            f'  m_Enabled: 1\n  m_EditorHideFlags: 0\n  m_Script: {{fileID: 11500000, guid: {script_guid}, type: 3}}\n'
            f'  m_Name: {name}\n  m_EditorClassIdentifier: {class_id}\n')

def make_mod_def(stat, kind, folder):
    """ModDef_Player_<Kind>_<Stat>. Display name auto-generated by OnValidate."""
    name = f'ModDef_Player_{kind}_{stat}'
    if name in INDEX:
        CREATED[name] = INDEX[name]['guid']; return
    template_map = {
        'AddNormal': 'Thêm thẳng {0}',
        'AddRatio':  'Thêm dựa trên gốc {0}%',
        'Multiply':  'Nhân tất cả x{0}',
    }
    body = so_header(SG['AssetModifierDefinition'], name, 'Assembly-CSharp::Luzart.AssetModifierDefinition')
    body += f'  _id: {name}\n  displayName: {template_map[kind]} {stat}\n'
    g = write_asset(folder, name + '.asset', body)
    CREATED[name] = g

def make_aggregation(name, folder, mode, numbers_refs):
    """AssetNumber_Aggregation. `mode`: 0=Sum, 1=Multiply. numbers_refs: list of (NumberMode, constant, asset_guid_or_None)."""
    if name in INDEX:
        CREATED[name] = INDEX[name]['guid']; return
    body = so_header(SG['AssetNumber_Aggregation'], name, 'Assembly-CSharp::Luzart.AssetNumber_Aggregation')
    body += f'  _id: {name}\n  aggregationMode: {mode}\n  numbers:\n'
    if not numbers_refs:
        # empty list — Unity needs explicit empty
        body = body.rstrip('  numbers:\n')
        body += '  numbers: []\n'
    else:
        for (n_mode, n_const, n_asset_guid) in numbers_refs:
            asset_field = f'{{fileID: 11400000, guid: {n_asset_guid}, type: 2}}' if n_asset_guid else '{fileID: 0}'
            body += (f'  - mode: {n_mode}\n    constant: {n_const}\n    asset: {asset_field}\n')
    g = write_asset(folder, name + '.asset', body)
    CREATED[name] = g

def make_constant(name, folder, value):
    if name in INDEX:
        CREATED[name] = INDEX[name]['guid']; return
    body = so_header(SG['AssetNumber_Constant'], name, 'Assembly-CSharp::Luzart.AssetNumber_Constant')
    body += f'  _id: {name}\n  value: {value}\n'
    g = write_asset(folder, name + '.asset', body)
    CREATED[name] = g

def make_simple_boosted(name, folder, base_guid, add_guid, mul_guid):
    if name in INDEX:
        CREATED[name] = INDEX[name]['guid']; return
    body = so_header(SG['AssetNumber_SimpleBoosted'], name, 'Assembly-CSharp::Luzart.AssetNumber_SimpleBoosted')
    body += f'  _id: {name}\n'
    body += '  baseNumber:\n    mode: 1\n    constant: 0\n    asset: {fileID: 11400000, guid: ' + base_guid + ', type: 2}\n'
    body += '  addNumber:\n    mode: 1\n    constant: 0\n    asset: {fileID: 11400000, guid: ' + add_guid + ', type: 2}\n'
    body += '  multiplyNumber:\n    mode: 1\n    constant: 0\n    asset: {fileID: 11400000, guid: ' + mul_guid + ', type: 2}\n'
    body += '  powNumber:\n    mode: 0\n    constant: 1\n    asset: {fileID: 0}\n'
    g = write_asset(folder, name + '.asset', body)
    CREATED[name] = g

def make_modifier(name, folder, definition_guid, contribution_guid):
    if name in INDEX:
        CREATED[name] = INDEX[name]['guid']; return
    body = so_header(SG['AssetModifier_ContributeToAggregatedNumber'], name, 'Assembly-CSharp::Luzart.AssetModifier_ContributeToAggregatedNumber')
    body += f'  _id: {name}\n'
    body += '  definition: {fileID: 11400000, guid: ' + definition_guid + ', type: 2}\n'
    body += '  factors: []\n'
    body += '  contributionNumber: {fileID: 11400000, guid: ' + contribution_guid + ', type: 2}\n'
    g = write_asset(folder, name + '.asset', body)
    CREATED[name] = g

# === Build infrastructure per stat ===
base_folder = 'Assets/_Main/Data/ModifierAndInGame/Player'
for stat, base_value in STATS:
    print(f'\n=== {stat} (base={base_value}) ===')
    stat_folder = f'{base_folder}/{stat}'
    def_folder = stat_folder + '/Definition'
    mod_folder = stat_folder + '/Modifier'

    # 1. Constant base number
    make_constant(f'Number_Player_InGame_Base_{stat}', stat_folder, base_value)

    # 2. ModDefs (3 kinds)
    for kind in ('AddNormal', 'AddRatio', 'Multiply'):
        make_mod_def(stat, kind, def_folder)

    # 3. AggregationNumbers
    #    Sum mode for TotalAddNormal, TotalAddRatio, TotalAddSubRatio (1 + ratio)
    #    Multiply mode for TotalMultiply
    make_aggregation(f'Number_Player_InGame_TotalAddNormal_{stat}', stat_folder, 0, [])
    make_aggregation(f'Number_Player_InGame_TotalAddRatio_{stat}',  stat_folder, 0, [])
    # SubRatio = sum of [Constant 1, TotalAddRatio]
    total_addratio_guid = CREATED[f'Number_Player_InGame_TotalAddRatio_{stat}']
    make_aggregation(f'Number_Player_InGame_TotalAddSubRatio_{stat}', stat_folder, 0,
                     [(0, 1, None), (1, 0, total_addratio_guid)])
    make_aggregation(f'Number_Player_InGame_TotalMultiply_{stat}', stat_folder, 1, [(0, 1, None)])

    # 4. Modifiers wired to their aggregation numbers
    make_modifier(f'Mod_Player_InGame_{stat}_AddNormal', mod_folder,
                  CREATED[f'ModDef_Player_AddNormal_{stat}'],
                  CREATED[f'Number_Player_InGame_TotalAddNormal_{stat}'])
    make_modifier(f'Mod_Player_InGame_{stat}_AddRatio', mod_folder,
                  CREATED[f'ModDef_Player_AddRatio_{stat}'],
                  CREATED[f'Number_Player_InGame_TotalAddRatio_{stat}'])
    make_modifier(f'Mod_Player_InGame_{stat}_Multiply', mod_folder,
                  CREATED[f'ModDef_Player_Multiply_{stat}'],
                  CREATED[f'Number_Player_InGame_TotalMultiply_{stat}'])

    # 5. Final SimpleBoosted = (Base + TotalAddNormal) × TotalAddSubRatio (we omit TotalMultiply for now)
    make_simple_boosted(f'Number_Player_InGame_Final_{stat}', stat_folder,
                        CREATED[f'Number_Player_InGame_Base_{stat}'],
                        CREATED[f'Number_Player_InGame_TotalAddNormal_{stat}'],
                        CREATED[f'Number_Player_InGame_TotalAddSubRatio_{stat}'])
    print(f'  {len([k for k in CREATED if stat in k])} SOs registered for {stat}')

# Dump map
with open('docs/created-guids-modifier-infra.json', 'w', encoding='utf-8') as f:
    json.dump(CREATED, f, ensure_ascii=False, indent=1)
print(f'\nDone. {len(CREATED)} SO references created/registered.')
